export enum Intent {
  FOLLOW_PLAYER = 'FOLLOW_PLAYER',
  STOP_FOLLOWING = 'STOP_FOLLOWING',
  HELP = 'HELP',
  GREETING = 'GREETING',
  UNKNOWN = 'UNKNOWN',
  PING = 'PING',
  REMEMBER_ME = 'REMEMBER_ME',
  WHO_AM_I = 'WHO_AM_I'
}
