export enum GoalType {
  FOLLOW_PLAYER = 'FOLLOW_PLAYER',
  STOP_FOLLOWING = 'STOP_FOLLOWING',
  ASSIST_PLAYER = 'ASSIST_PLAYER',
  IDLE = 'IDLE',
  COME_HERE = 'COME_HERE',
  STAY_HERE = 'STAY_HERE',
}
